apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dbaas-catalog
  namespace: olm
spec:
  displayName: DBaaS Platform Catalog
  publisher: DBaaS Community
  sourceType: grpc
  image: ghcr.io/percona/dbaas-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
