name: Build and Push image

on:
  push:
    branches: [ main ]
    tags:
      - v*
  workflow_dispatch:

jobs:

  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set latest tag
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "image_tag=latest" >> $GITHUB_ENV

      - name: Set release tag
        if: ${{ github.ref_name != 'main' }}
        run: |
          echo "image_tag=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/percona/dbaas-catalog
          tags: ${{ env.image_tag }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: . 
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: dbaas-catalog.Dockerfile

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: dbaas-catalog.Dockerfile
